# The electron-builder config for the staging site (https://dev.shieldbattery.net)
# It should generally match the other build configs (except things that need to differ for this
# "region")
appId: net.shieldbattery.client.dev
extraResources:
  - game/dist/**
files:
  - '!**/*.map'
  - '!build/**/*'
  - '!node_modules/**/*'
  - 'index.html'
  - 'assets/**/*'
  - 'dist/bundle.js'
  - 'dist/**/*.chunk.js'
  - from: 'dist/'
    to: './'
    filter:
      - 'index.js'
  - from: 'dist/'
    to: './native/'
    filter:
      - '**/process.js'
      - '**/*.node'
nsis:
  artifactName: '${productName}-setup-${version}.${ext}'
  # We disable oneClick for this config so that the install directory differs for this version
  oneClick: false
win:
  icon: icon.ico
  target: nsis-web

# These properties differ between configs
productName: ShieldBattery-Staging
publish:
  provider: generic
  url: 'https://staging.shieldbattery.net/published_artifacts/${os}'
